# Set the hostnames of the machines you want to use. These must match entries in
# your ssh config file. You should also ensure that these entries are configured
# to use an IdentityFile pointing to an ssh key without password. Note that SSH
# Agent is not supported.
#
# Example of an .ssh/config file entry defining the host named `host_a`:
#
# Host host_a
#    HostName host1.example.com
#    User user
#    IdentityFile ~/.ssh/id_rsa
#
[hosts]
controller = ""
pktgen = ""


# Set the paths where to copy the source code on both the controller and the
# pktgen machines.
# Ensure that the user you are using to ssh into the machines has write access
# to these directories. This user is set in the .ssh/config file (see above).
[paths]
controller_path = ""
dataplane_path = ""
sde_install = ""
controller_build_script = ""
dataplane_build_script = ""
pktgen_path = ""


[devices.controller]


[devices.pktgen]
rx_dev = "0000:00:00.0"
tx_dev = "0000:00:00.0"
tx_line_rate = -1 # in Gbps.
nb_tx_cores = -1

[logs]
# Log files. They will be saved in the orchestrator machine in the same
# directory where you run the experiment.py script.
controller_log = "controller.log"
pktgen_log = "pktgen.log"


[extra]
dpdk_mem_channels = 4
